[package]
name = "metaimage"
version = "0.1.2"
edition = "2024"

[dependencies]
bytemuck = { version = "1.25.2", features = ["must_cast"] }
flate2 = { version = "1.1.9", default-features = false, features = ["zlib-rs"] }
ndarray = ">=0.16, <0.18"

[dev-dependencies]
criterion = "0.8.2"
which = "8.0.5"

[[bench]]
name = "io"
harness = false
